mi6/ic-design-system

- src/content/structured/components/hero/guidance.mdx
- src/content/structured/components/links/guidance.mdx
- src/content/structured/components/loading-indicators/guidance.mdx
- src/content/structured/components/page-header/guidance.mdx
- src/content/structured/components/radio/guidance.mdx
- src/content/structured/components/search-bar/guidance.mdx
Fix duplicate nav priority and the following nav priorities until the order had realigned.
> fix(root): fix duplicate nav priority

- README.md
Fixes links to ic-ui-kit repo
#70
> fix(root): fix broken links in README

- package-lock.json
- package.json
Reverted gatsby-transformer-remark back to 5.2.0
> revert(root): reverted package back to avoid conflicting peer dependency

- .github/workflows/ic-design-system-main.yml
- src/components/Layout/index.tsx
- src/config.js
Added a meta tag to the site head section containing an authentication token for Google Search Console. Updated the main build step to set the related environment variable.
[64](https://github.com/mi6/ic-design-system/issues/64)
> Implement google search console

- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/radio/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/search-bar/guidance.mdx
- src/content/structured/components/select/code.mdx
- src/content/structured/components/select/guidance.mdx
- src/content/structured/components/stepper/code.mdx
- src/content/structured/components/tabs/code.mdx
- src/content/structured/components/tabs/guidance.mdx
Add more code examples to clarify how our components can be used
More examples having been added for the following components:
- Breadcrumbs
- Card
- Page header
- Radio
- Search bar
- Stepper
- Tabs
#14
> Add more code examples for breadcrumbs, card, page header, radio, search bar, stepper and tabs component

- src/content/structured/components/checkboxes/code.mdx
- src/content/structured/components/classification-banner/code.mdx
- src/content/structured/components/footer/code.mdx
- src/content/structured/components/hero/code.mdx
- src/content/structured/components/links/code.mdx
- src/content/structured/components/loading-indicators/code.mdx
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/select/code.mdx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/text-input/code.mdx
- src/content/structured/components/top-nav/code.mdx
Increase code examples of checkboxes, classification banner, footer, hero, links, loading, select, side nav, skeleton, switch, text field and top nav
#14
> feat(root): increase code examples

- src/content/static/components/CookiesData/CookiesCards.tsx
- src/content/static/components/CookiesData/CookiesTable.tsx
- src/content/static/components/CookiesData/cookies.css
- src/content/static/components/CookiesData/index.tsx
- src/content/structured/accessibility/requirement/index.mdx
- src/content/structured/icds/cookies-policy.mdx
- src/utils/helpers.ts
Built responsive cookies table which switches from cards in XS to MD to a table from LG and greater
N/A
> feat(root): added responsive cookies table

- src/content/structured/components/tabs/guidance.mdx
- src/content/structured/get-started/custom-theme.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/testing-components.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
Add testing documentation for Jest. Update nav priority for addition of new page
#96
> docs(root): add testing documentation for Jest

- package-lock.json
Regenerated package-lock file for latest components
N/A
> build(root): regenerated package-lock file

- package-lock.json
- src/components/CookieBanner/cookies.helper.ts
Update to cookie delete method as regex was causing issues with Safari. This has been fixed. 
N/A
> Release: Fix Safari Bug

- src/content/structured/components/chips/guidance.mdx
Update static chips to h5 to match dismissible chips
> fix(root): update static chips to h5

- src/components/CodePreview/index.css
- src/components/SubsectionNav/index.css
Fixed issues with WHCM for left hand nav (selected page indicator fixed) and code snippet (code syntax highlighting maintained)
> High contrast fixes

- CONTRIBUTING.md
Update line about signed commits in CONTRIBUTING.md.
Continuation of mi6/ic-ui-kit#13
> docs(root): update line about signed commits in CONTRIBUTING.md

- src/components/Search/index.tsx
Prevented search bar from using results based on outdated value
#101
> fix(root): fixed search bar updating results

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/delete-gh-pages-folder.yml
Added action to add qa link to issue and remove build folder when branch is deleted
15 (in ic-ui-kit)
> feat(root): added two new gh actions

- src/content/structured/components/classification-banner/accessibility.mdx
- src/content/structured/components/classification-banner/code.mdx
- src/content/structured/components/classification-banner/guidance.mdx
Removed top-secret, secret and official classification banners to prevent confusion
> fix(root): removed classification of pages

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/auto-add-new-issues-to-project.yaml
- .github/workflows/delete-gh-pages-folder.yml
Fixed on trigger for deleting folder workflow
> fix(root): fixed broken workflow

- gatsby-config.js
- package-lock.json
- package.json
- src/components/Permalink/index.css
- src/components/Permalink/index.tsx
- src/components/WrappedH2/index.css
- src/components/WrappedH2/index.tsx
- src/components/WrappedH3/index.css
- src/components/WrappedH3/index.tsx
- src/templates/CoreTemplate/index.css
added tooltip to permalink, improved position within headings and changed to a iconbutton appearance. removed dependency.
fix #24
> fix(root): improve permalink layout and usability

- src/components/Search/index.tsx
Fixes issue where typed in value was left in input after item selected and subsequent navigation
> fix(root): fixes search issue

- src/content/structured/get-started/react.mdx
Adds details on config steps required to transpile React component package for use in NextJS.
#178
> docs(root): adds instructions for NextJS

- src/content/structured/accessibility/definition.mdx
- src/content/structured/accessibility/discussing.mdx
- src/content/structured/accessibility/documenting/accessibility-statements-guidance.mdx
- src/content/structured/accessibility/index.mdx
- src/content/structured/accessibility/requirement/index.mdx
- src/content/structured/accessibility/requirement/wcag.mdx
- src/content/structured/community/contribute-criteria.mdx
- src/content/structured/community/index.mdx
- src/content/structured/components/buttons/guidance.mdx
- src/content/structured/components/search-bar/guidance.mdx
- src/content/structured/components/select/guidance.mdx
- src/content/structured/get-started/a-design-system.mdx
- src/content/structured/get-started/custom-theme.mdx
- src/content/structured/get-started/figma.mdx
- src/content/structured/get-started/releases-versioning.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/web-components.mdx
- src/content/structured/icds/accessibility-statement.mdx
- src/content/structured/icds/privacy-policy.mdx
- src/content/structured/styles/colour.mdx
- src/content/structured/styles/icons.mdx
- src/content/structured/styles/layout-spacing.mdx
- src/content/structured/styles/motion.mdx
- src/content/structured/styles/templates.mdx
- src/content/structured/styles/typography.mdx
Update first page headings to be more descriptive, and update some component pages to improve heading and demo consistency
#35
> docs(root): update the first page headings on some pages to be more descriptive

- src/content/structured/accessibility/definition.mdx
- src/content/structured/accessibility/discussing.mdx
- src/content/structured/accessibility/documenting/accessibility-statements-guidance.mdx
- src/content/structured/accessibility/index.mdx
- src/content/structured/accessibility/requirement/index.mdx
- src/content/structured/accessibility/requirement/wcag.mdx
- src/content/structured/community/contribute-criteria.mdx
- src/content/structured/community/index.mdx
- src/content/structured/components/buttons/guidance.mdx
- src/content/structured/components/data-entity/code.mdx
- src/content/structured/components/search-bar/guidance.mdx
- src/content/structured/components/select/guidance.mdx
- src/content/structured/get-started/a-design-system.mdx
- src/content/structured/get-started/custom-theme.mdx
- src/content/structured/get-started/figma.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/releases-versioning.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/web-components.mdx
- src/content/structured/icds/accessibility-statement.mdx
- src/content/structured/icds/privacy-policy.mdx
- src/content/structured/styles/colour.mdx
- src/content/structured/styles/icons.mdx
- src/content/structured/styles/layout-spacing.mdx
- src/content/structured/styles/motion.mdx
- src/content/structured/styles/templates.mdx
- src/content/structured/styles/typography.mdx
- src/templates/CoreTemplate/index.css
Merge develop to main with 2.1.0-beta.3 packages
> [release]: 2.1.0-beta.3 Develop > Main

- src/content/structured/get-started/gatsby.mdx
Documentation page created for using @ukic components in Gatsby.
To review changes please see 'Get Started -> Get Components -> Gatsby'
> Gatsby documentation

- src/components/AttributeCards/index.css
- src/components/AttributeCards/index.tsx
- src/components/AttributeTable/index.css
- src/components/CodeAttribute/index.css
- src/components/ComponentDetails/PropTable/PropDescription/index.css
- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/PropName/index.css
- src/components/ComponentDetails/PropTable/PropName/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
Add required status to props table on component code pages. Add attribute to prop name column. Sort props table so required props appear first
#149,  #233
> docs(root): add required status to props description in props table 

- src/content/structured/get-started/custom-theme.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/testing-with-react-testing-library.mdx
Testing documentation with using RTL has been added to the guidance site in order to assist development teams test ukic/react components within their applications
https://github.com/mi6/ic-ui-kit/issues/282
> docs(root): documentation about testing with RTL

- src/content/structured/components/search-bar/code.mdx
Adds an example where the options provided to search bar can be provided from an external source.
#231
> docs(root): adds example of search bar with async filtering

- gatsby-browser.js
- gatsby-ssr.js
- package-lock.json
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/cards/guidance.mdx
Add code examples for card v2 changes.
#204
> Add card v2 code examples

- src/content/structured/accessibility/documenting/conformance-report.mdx
- src/content/structured/accessibility/testing/automated-testing.mdx
Updated accessibility content and links
N/A
> docs(root): 273 accessibility updates

- src/content/structured/components/back-to-top/code.mdx
Fix typo in back to top code examples from targetId to target and update kebab cased heading to remove '-'
#241
> fix(root): fix typo in back to top code examples from targetId to target

- src/content/structured/accessibility/introduction.mdx
The site references ADHD Aware which states up to 15% of people are neurodiverse. The incorrect percentage has now been corrected to 15%
#245
> Update percentage of people who are neurodiverse in the accessibility section

- src/content/structured/accessibility/introduction.mdx
Update accessed by date for a reference on the  intro to accessibility page
#245
> docs(root): update accessed by date for a reference on the  intro to accessibility page

- .github/workflows/ic-design-system-main.yml
Added token property to deploy with branch permissions
#130
> build(root): updated action to include PAT 

- src/content/structured/get-started/react.mdx
Update to SlottedSVG guidance to reflect recent component changes allowing SlottedSVG have embedded path as well as passing the path as a prop.
N/A
> docs(root): update to SlottedSVG guidance to reflect component changes

- src/content/structured/components/cards/code.mdx
Adds examples to show off latest interactive card component changes
#204
> docs(root): Adds extra code examples for cards

- src/content/structured/components/alerts/code.mdx
- src/content/structured/components/buttons/code.mdx
- src/content/structured/components/checkboxes/code.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/data-entity/code.mdx
- src/content/structured/components/radio/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/tabs/code.mdx
- src/content/structured/components/text-input/code.mdx
Cleaned up events within code snippets and previews. Added events to more examples to show how they are applied
Closes #276
#276
> docs(root): update events within code snippets

- .github/workflows/check-pr-target.yml
Prevents PRs being raised against main unless source is develop
> build(root): adds check for PR target

- .github/workflows/check-pr-target.yml
Changes PRs to target develop if initially raised against main
> build(root): changes PR target to develop

- src/content/structured/components/cards/code.mdx
Updates clickable button example with onClick handler code
> docs(root): adds onClick code to card example

- .github/workflows/ic-design-system-branches.yml
- .github/workflows/ic-design-system-main.yml
- audit-ci.json
- package-lock.json
- package.json
Add npm audit to scripts and add to branches and main workflows
419 in the ui-kit
> build(root): add npm audit to scripts and add to workflows

- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/select/code.mdx
Adds an example to show asynchronously updating the options in the select on a delay as the user types
Also makes slight changes to ic-search-bar to fix syntax highlighting 
#326
> docs(root): adds example of external filtering for ic-select

- src/content/structured/get-started/test-components.mdx
- src/content/structured/get-started/testing-with-cypress.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/testing-with-react-testing-library.mdx
Guidance added on testing @UKIC components with Cypress testing library and navigation priority added to each testing page.
#291
> docs(root): added documentation for testing with Cypress

- src/content/structured/components/select/code.mdx
- src/content/structured/components/select/guidance.mdx
Updates examples to remove setting value in IcChange handler
> docs(root): updates select code examples

- src/components/AnchorNav/index.css
- src/components/Header/index.tsx
Enables sticky page header on desktop viewport and fixes issue where anchor nav would disappear behind header
#168
> fix(root): enables sticky page header and fixes anchor nav

- src/content/structured/community/roadmap.mdx
Updated roadmap with recent changes and future plans. Added popover into recently added as by the time this is on the live site, popover will be released.
#382
> docs(root): update roadmap with recent changes and future plans

- src/content/structured/community/roadmap.mdx
Update the wording of the roadmap page.
> docs(root): update roadmap page

- .github/workflows/check-versions-to-develop-design-system.yml
- .github/workflows/release-design-system.yml
Automate updating of versions, create check-versions -> develop PR then delete check-versions branch and create develop -> main PR
#384
> ci(root): automate updating of versions and check-versions -> develop PR

- src/components/Layout/index.tsx
Adds back-to-top to landing page
https://github.com/mi6/ic-design-system/issues/338
> Back to top not on landing page 338

- .github/workflows/ic-design-system-branches.yml
- mdx-to-json-settings.json
- src/components/Layout/index.tsx
- src/content/structured/components/toasts/code.mdx
This is a replication of the workflow work done in `ic-ui-kit`. Add additional trigger events on CI build so tests can be run on forked repos which are contributing to base develop branch. Add condition to deploy step on feature branch CI build to prevent the deploy step from running on external contributions
> ci(root): update branch CI workflow to run tests on contributor code

- src/content/structured/styles/elevation.mdx
Fixed broken link to tooltips page
> fix(root): fixed broken link

- package-lock.json
- src/content/structured/styles/components/IconFinder/index.css
removes unwanted gap on icons panel and adds some padding to title to align panel headers
https://github.com/mi6/ic-design-system/issues/387
> fix(root): removes unwanted gap from icons panel

- audit-ci.json
- package-lock.json
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/text-input/code.mdx
Fixes package-lock as had incorrect react component version. Also resolves some lint and audit errors causing ci build to fail
N/A
> chore(root): fix package-lock

- .github/workflows/ic-design-system-branches.yml
Additional github action triggers added. Updated deploy step so it is skipped if external contributors. This update mirrors the feature branch workflow for `ic-ui-kit`
N/A
> fix(root): updated github action to mirror ic-ui-kit

- src/content/structured/components/tabs/code.mdx
Add nested tabs code example. You'll need to run npm pack for web-components and react on develop in the ui kit and install those locally to see the example working.
#423
> docs(root): add nested tabs code example

- audit-ci.json
Fixes audit issue causing build to fail
N/A
> chore(root): fixes audit issue

- src/content/structured/community/roadmap.mdx
> docs(root): roadmap update

- README.md
Fixed the raise an issue link to point at the ic-design-system not the ic-ui-kit
447
Fixed the raise an issue link to point at the ic-design-system not the ic-ui-kit
[447](https://github.com/mi6/ic-design-system/issues/447)
> fix(docs): updated link to point to the correct repository

- src/content/structured/components/tooltips/code.mdx
added code example to tooltip with new public method
#455
> docs(root): added code example to tooltip

- src/content/structured/components/pagination/code.mdx
- src/content/structured/components/pagination/guidance.mdx
Fix code examples for pagination & prettier fix on pagination guidance page
N/A
> docs(root): fix code examples for pagination & prettier fix on pagination guidance page

- src/content/structured/components/breadcrumbs/code.mdx
Updates breadcrumb 'With React Router' code snippet and demo so breadcrumb styling is correct
https://github.com/mi6/ic-design-system/issues/360
> fix(root): updates react snippet so breadcrumb styling is correct

- .github/workflows/check-versions-to-develop-design-system.yml
Update workflow to remove the local branch created as the action creates it itself
#479
> fix(root): update workflow to remove the local branch created

- src/content/structured/components/typography/code.mdx
Add code example for truncation in typography. Will need to pull down 345-add-see-more-truncation-pattern-for-typography in the ui kit to test locally as see more pattern hasn't been released yet.
#470
> docs(root): add code example for truncation in typography

- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/page-header/guidance.mdx
New PR for https://github.com/mi6/ic-design-system/pull/365
#316
> Status tag chip fix

- package-lock.json
- src/content/structured/get-started/testing-with-cypress.mdx
- src/content/structured/styles/elevation.mdx
fixed broken links in testing and elevation pages
> fix(root): fixed broken links

- src/content/structured/components/pagination/accessibility.mdx
- src/content/structured/components/pagination/code.mdx
- src/content/structured/components/pagination/guidance.mdx
Bug fixes to pagination docs
#464
> fix(root): bug fix in pagination docs

- gatsby-browser.js
- gatsby-config.js
- gatsby-ssr.js
- src/content/structured/components/side-nav/code.mdx
- src/pages/side-navigation-layout.tsx
- src/utils/paths.ts
> fix(root): see internal issue 2336

- audit-ci.json
- src/content/structured/components/skeleton/code.mdx
Example of ic-skeleton being used within ic-card has been added to the skeleton code examples
#475
> 475 ic skeleton an example of using the skeleton in a card

- .github/workflows/ic-design-system-branches.yml
- audit-ci.json
Updated github action to run manually using the workflow dispatch and removed ci skip task
N/A
> ci(root): removed skip jobs and push trigger

- src/components/Search/index.tsx
Add loading to search bar to prevent searching for search term returning wrong options
#509
> fix(root): add loading to search bar

- src/content/structured/get-started/design-principles.mdx
Added design principle about sustainability.
> docs(root): add sustainability design principle

- src/components/ComponentDetails/MethodTable/index.tsx
- src/components/ComponentDetails/SlotTable/index.tsx
Update slots and methods cards to use same styling as props/events - using AttributeName.
#388
> style(root): update slots and methods cards to use same styling as props/events

- audit-ci.json
- package-lock.json
- src/content/structured/components/skeleton/code.mdx
removed incorrect height declaration to match actual code example
#502
> docs(root): removed incorrect height declaration

- src/components/Header/index.tsx
Update component code/accessibility tabs to use path for href so that anchor links work as expected. This now causes a page refresh on each tab click, however this seems to be the only way to have the correct anchor link behaviour due to the url needing to contain the tab name, and with a change in url the expected behaviour is a page refresh.
To show that this works, you will have to do pull down the changes locally and do npm run build and npm run serve
#237
> fix(root): update href to path for component tabs

- package-lock.json
Updated semver using audit fix to patch vulnerabilities
This is a recreation of https://github.com/mi6/ic-design-system/pull/530 due to an error updating the branch.
> chore(root): updated semver version using audit fix

- .github/workflows/release-design-system.yml
update develop -> main PR automation to use github api
> ci(root): update develop -> main PR automation to use github api

- package-lock.json
Updated word-wrap package in package-lock by ruhning `npm audit fix`
N/A
> chore(root): updated word-wrap package

- src/content/structured/components/data-entity/code.mdx
- src/content/structured/components/dialog/code.mdx
- src/content/structured/components/dialog/guidance.mdx
- src/content/structured/components/popover-menu/code.mdx
- src/content/structured/components/popover-menu/guidance.mdx
- src/content/structured/components/tooltips/code.mdx
Update react code examples to use useRef instead of document.querySelector
#522
> docs(root): update react code examples to use useRef

- src/components/Layout/index.tsx
- src/components/TopNavWrapper/index.tsx
- src/config.js
- src/content/structured/components/top-nav/code.mdx
Add short title to top navigation and code example to top navigation component page.
Will need to test locally until [the ui-kit change](https://github.com/mi6/ic-ui-kit/pull/901) has been merged into main.
[853 in ui-kit](https://github.com/mi6/ic-ui-kit/issues/853)
> feat(root): add short title to top navigation

- src/content/structured/styles/colour.mdx
- src/content/structured/styles/components/ColourTable/colours.config.ts
- src/content/structured/styles/components/ColourTable/index.css
- src/content/structured/styles/components/ColourTable/index.tsx
Update colours page to include new variables and deprecated variables.
(https://github.com/mi6/ic-ui-kit/pull/985)
> docs(root): update colours page to include new variables

- src/content/structured/get-started/testing-with-react-testing-library.mdx
Add missing import to test documentation for react testing library.
#506
> docs(root): add missing import to test documentation

- audit-ci.json
Update audit-ci.json to unblock failing PRs
> chore(root): update audit-ci.json

- src/content/structured/components/dialog/guidance.mdx
Addressed lorem ipsum text on 'guidance'. The changes on 'code' will be done separately.
#533
> Lorem ipsum in dialog component demos first #533

- src/content/structured/components/footer/code.mdx
- src/pages/footer-layout.tsx
- src/utils/paths.ts
adds example of how to place footer below page fold
Adds code example of how to push footer below page fold
#551
> feat(root): adds example of how to place footer below page fold

- src/content/structured/community/contribute.mdx
Fixed missing instructions and added new instructions in prep for adding our Figma UI Kit to the Figma community.
> Missing instructions to figma contribution model #332

- src/content/structured/get-started/figma.mdx
Updated Figma instructions for external only users.
> Update figma instructions for external users.mdx

- src/content/structured/components/footer/code.mdx
fixed code snippet that wasn't correct for the language it was written for
> fix(root): fixed inaccurate code snippet

- audit-ci.json
Adds "GHSA-7fh5-64p2-3v2j" to audit-ci.json
N/A
> chore(root): fix postcss audit error

- package-lock.json
- package.json
bumps version to fix dependabot issue
N/A
> chore(root): bump gatsby-transformer-remark version

- .husky/pre-commit
- src/content/structured/components/accordion/accessibility.mdx
- src/content/structured/components/accordion/code.mdx
- src/content/structured/components/accordion/guidance.mdx
- src/content/structured/components/badge/accessibility.mdx
- src/content/structured/components/badge/code.mdx
- src/content/structured/components/badge/guidance.mdx
Add prettier check to precommit hook and run prettier (changes made to accordion mdx files and badge mdx files)
#568
> chore(root): add prettier check to precommit hook

- src/content/structured/components/accordion/accessibility.mdx
- src/content/structured/components/accordion/code.mdx
Update accordion code examples to show nested behaviour and run prettier:fix
> docs(root): update accordion code examples

- audit-ci.json
removed vulnerability references from audit-ci that are no longer an issue
> build(root): removed outdated vulnerabilities

- audit-ci.json
Added GHSA-wf5p-g6vw-rhxx to allow list
> chore(root): npm audit fix

- src/content/static/components/InlineCookiesManager.tsx
Fixes cookie switch not saving preferences. Caused by using web-components version of ic-switch rather than React version, which you cannot assign functions to inline
#681
> fix(root): fixes cookie switch

- audit-ci.json
- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
Changed order of getting started steps. Switched around CSS and adding component to improve flow of adding initial component
N/A
> docs(root): updated getting started docs

- src/content/structured/components/toasts/code.mdx
- src/content/structured/components/toasts/guidance.mdx
Update code examples to use openToast prop for toast region and add displaying toast explanation and more in-depth example of queuing.
Will need to build locally until the next release.
#675
> docs(root): update code examples to use openToast prop for toast region

- src/content/structured/components/typography/code.mdx
- src/content/structured/components/typography/guidance.mdx
Update guidance and code examples for typography to include more information about styling vs semantic headings, and to show different styling/variants of typography
#621
> docs(root): update guidance and code examples for typography

- audit-ci.json
audit ci vulnerability added
N/A
> chore(root): audit ci vulnerability added

- src/content/structured/community/roadmap.mdx
update the roadmap to reflect what we have worked on and working on
Roadmap update to latest version
#661
> docs(root): roadmap update to latest version

- src/components/SubsectionNav/index.tsx
Fixes focus issue in Firefox
#564
> fix(root): fixes focus issue on navigation panel

- src/content/structured/get-started/angular.mdx
Add skipLibCheck step into angular guidance.
#737
> docs(root): add skipLibCheck step into angular guidance

- src/content/structured/get-started/install-components.mdx
Add detail around usage of 3rd party libraries get started pages
Add detail around usage of 3rd party libraries to getting started page
#709
> docs(root): add detail around usage of 3rd party libraries get started pages

- src/content/structured/get-started/angular.mdx
Add guidance to angular set up about standalone components, not just modules.
#738
> docs(root): add guidance to angular set up about standalone components

- src/content/structured/components/checkboxes/code.mdx
- src/content/structured/components/radio/code.mdx
Update radio and checkbox conditional dynamic examples so that they don't move when the additional field shows
#655
> docs(root): update radio and checkbox conditional dynamic examples

- audit-ci.json
Updating audit entry for gatsby and markdown dependencies
N/A
> chore(root): updating audit file

- src/content/structured/components/alerts/code.mdx
- src/content/structured/components/badge/code.mdx
- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/data-entity/code.mdx
- src/content/structured/components/footer/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/section-container/code.mdx
- src/content/structured/components/select/code.mdx
- src/content/structured/components/tabs/code.mdx
- src/content/structured/components/tooltips/code.mdx
- src/content/structured/components/top-nav/code.mdx
All code examples for each component have been reviewed and changes have been made to the code examples that had errors within them when they were copied straight into a project. Errors have been resolved.
#434
> fix(root): fix errors within provided code examples

- src/content/structured/styles/grammar.mdx
Indicate use of when to use block capitals or not, including exceptions.
Changes to the content style pages to indicate exceptions for using block capitals. 
#377
> docs(#377): update grammar guidance on capitilisation

- src/pages/404.css
- src/pages/404.tsx
Updated 404 page and removed custom CSS with use of error state component. 
Re-opened on behalf of @MI6-94
> feat(root): aligned 404 page to use error state component

- src/content/structured/get-started/releases-versioning.mdx
Update CHANGELOG.md link to point at the web components changelog. 
#813
> docs(root): update changelog link

- package-lock.json
- src/components/Header/index.tsx
- src/components/Layout/index.tsx
Updated IP dependency due to dependabot notification. 
N/A
> build(root): updated dependencies

- audit-ci.json
- src/content/structured/components/badge/code.mdx
Update icon badges to have an aria label to add more context for screen readers
https://github.com/mi6/ic-ui-kit/issues/1518
> docs(root): update icon badges to have an aria label

- src/content/structured/components/buttons/code.mdx
Add code examples for dropdown and file upload buttons
#845
> docs(root): add code examples for dropdown and file upload buttons

- audit-ci.json
add vulnerability to allowlist for audit fix
> chore(root): add vulnerability to allowlist

- src/content/structured/components/toggle-buttons/code.mdx
Import toggle button group in toggle button code page
> docs(root): import toggle button group

- src/content/structured/components/tooltips/accessibility.mdx
Update tooltip accessibility guidance to explain the internal silent prop
#622
> docs(root): update tooltip accessibility guidance

- src/components/SubsectionNav/index.css
- src/templates/Standard/index.css
Fixes navigation styling to match page header colour
#403
> fix(root): fixes navigation styling on small devices

- src/components/ComponentDetails/EventTable/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
Update props and events tables to include statement on native props/events
#859
> 859 add built in events to website documentation

- audit-ci.json
- package-lock.json
Upgrades some packages to resolve audit issues
> chore(root): fixes some audit issues

- .github/workflows/scorecards.yml
- README.md
- audit-ci.json
Add openssf scorecard to github workflows and add badge to readme file
https://github.com/mi6/ic-ui-kit/issues/1215
> ci(root): add openssf scorecard to github workflows

- .github/workflows/scorecards.yml
- package-lock.json
Update publish_results to be false in scorecard.yml
N/A
> fix(root): update publish_results to be false in scorecard.yml

- src/content/structured/community/contribute.mdx
- src/content/structured/community/glossary-of-terms.mdx
- src/content/structured/get-started/install-components.mdx
- Updated 'get the components' to 'install the components' to cover what's required in the ticket
- Added glossary of terms to contribution guidance - copied from contribution guide in the ui kit repo
#666
> 666 get the components to install the components + add glossary of terms to docs

- .github/workflows/add-qa-link-to-issues.yml
- Update branch deployment link in Github workflow
> ci(root): update branch deployment link

- .github/workflows/ic-design-system-branches.yml
Add path prefix env variable for branch deployments
> ci(root): add path prefix env variable for branch deployments

- .github/workflows/ic-design-system-branches.yml
- src/components/TopNavWrapper/index.tsx
- update branch deployment path prefix
> update branch deployment path prefix

- package-lock.json
> build(root): audit fix

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/auto-add-new-issues-to-project.yaml
- .github/workflows/check-pr-target.yml
- .github/workflows/check-versions-to-develop-design-system.yml
- .github/workflows/delete-gh-pages-folder.yml
- .github/workflows/ic-design-system-branches.yml
- .github/workflows/ic-design-system-main.yml
- .github/workflows/release-design-system.yml
- .github/workflows/welcome-new-contributors.yml
- README.md
Update github workflows to fix scorecard issues and remove scorecard badge from readme as we don't publish results so it won't ever have a valid repo url.
#883
> chore(root): update github workflows to fix scorecard issues

- src/content/structured/patterns/components/StackblitzButton/stackblitz-helpers.ts
New change:
fix(root): move CSS for patterns to head tag and add anonymous crossorigin
> Develop > Main

- .github/workflows/check-versions-to-develop-design-system.yml
- .github/workflows/release-design-system.yml
Added contents:write to Github action so the CI is able to create PRs
N/A
> fix(root): added content write permissions to release actions

- src/content/structured/components/cards/guidance.mdx
> fix(root): fixed cards anchor link

- .github/workflows/check-pr-target.yml
- .github/workflows/check-versions-to-develop-design-system.yml
- .github/workflows/delete-gh-pages-folder.yml
- .github/workflows/ic-design-system-branches.yml
- .github/workflows/ic-design-system-main.yml
- .github/workflows/release-design-system.yml
- .github/workflows/welcome-new-contributors.yml
Added granular permissions for Github Actions. The granular permissions are required due to the additional security config.
N/A
> fix(root): updated github actions

- src/content/structured/community/index.mdx
- src/content/structured/community/roadmap.mdx
Updated roadmap to reflect recent work, made small changes to community overview page
> docs(root): updated roadmap to reflect recent work

- src/components/AnchorNav/index.tsx
- src/components/AttributeCards/index.tsx
- src/components/AttributeTable/index.tsx
- src/components/ComponentDetails/EventTable/index.tsx
- src/components/ComponentDetails/MethodTable/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
- src/components/ComponentDetails/SlotTable/index.tsx
- src/components/ComponentDetails/StyleTable/index.tsx
- src/components/ComponentGallery/index.tsx
- src/components/Layout/index.tsx
- src/components/SubsectionNav/index.tsx
- src/content/structured/components/accordion/guidance.mdx
- src/content/structured/styles/colour.mdx
- src/content/structured/styles/components/ColourTable/index.tsx
- src/content/structured/styles/components/IconFinder/index.tsx
- src/icds-pages-data.json
- src/templates/Homepage/index.tsx
- src/utils/helpers.tsx
Resolve console errors regarding footer logos, including the ones pictured below:
A full list of the console errors can be seen in your local build of the `develop` branch.
> fix(root): resolve console errors related to having a React key when using the map() method

- src/content/structured/components/badge/guidance.mdx
punctuality changes to capital letters
> docs(root): punctuality changes

- src/content/structured/components/buttons/guidance.mdx
Added icon button to match the description of five button variants
> docs(root): added icon button

- src/components/CodePreview/index.tsx
Fixes copy code icon that was cropped on smaller devices
#966
> fix(root): fixes copy code icon on small devices

- src/content/structured/styles/components/ColourTable/colours.config.ts
> docs(root): typo in color token

- src/content/structured/components/date-picker/guidance.mdx
fixed typo on date picker page
> docs(root): fixed typo on date picker page

- .github/workflows/check-versions-to-develop-design-system.yml
Added `contents: write` permission so github action can update branch for release.
N/A
> fix(root): added contents permission to add to branch

- src/components/CookieBanner/cookies.css
- src/components/CookieBanner/index.tsx
- src/components/Layout/index.tsx
- src/components/SubsectionNav/index.tsx
- src/components/TopNavWrapper/index.tsx
Fixes issue where bottom elements in navigation bar could not be seen without scrolling main content
#139
> fix(root): fixes navigation bar scrolling

- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
build was failing because of type mismatch, have typed propData as stencilProp
> fix(root): change proptable type to fix build

- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
- src/components/CookieBanner/cookies.css
- src/components/CookieBanner/index.tsx
- src/components/Layout/index.tsx
- src/components/SubsectionNav/index.tsx
- src/components/TopNavWrapper/index.tsx
Develop merge into main, with fix for proptable and nav bar scrolling!
> Develop -> Main for Release

- src/content/structured/components/select/code.mdx
- src/content/structured/components/select/guidance.mdx
New PR as #986 rebase went wrong
Update select code and guidance to show custom elements and icons
#601
> docs(root): update select code and guidance to show custom elements

- audit-ci.json
Adds to allowlist for vulnerability in "ip" package - no current patch available
N/A
> chore(root): adds to allowlist for audit

- package-lock.json
Updates braces package for audit issue
N/A
> chore(root): updates braces package for audit issue

- audit-ci.json
Updates allow list for ws as cannot upgrade package
N\A
> chore(root): audit fix

- src/components/ComponentGallery/index.tsx
Removed the status tag from the component gallery 
#981
> docs(root): removed status tag from component gallery

- audit-ci.json
Adds to allowlist for socket.io package issue
> chore(root): adds to allowlist for audit issue

- src/content/structured/get-started/test-components.mdx
Add alert to testing page to explain issues with Mocha
N/A
> Alert for mocha issues

- src/content/structured/components/date-picker/guidance.mdx
- src/icds-pages-data.json
Removes typo on date-picker guidance page
N/A
> docs(root): fixes issue on date-picker guidance

- src/components/CodePreview/index.css
- src/components/CodePreview/index.tsx
- src/icds-pages-data.json
Makes code snippet area focusable to fix accessibility issue
#833
> fix(root): makes code snippet area focusable

- .github/workflows/update-v3-branch.yml
- src/components/CodePreview/types.ts
Apply workflows related to the develop branch to v3.0.0/develop branch as well as workflow to keep
v3.0.0/develop branch up-to-date with the develop branch.
https://github.com/mi6/ic-ui-kit/issues/2058
> ci(root): apply workflows to v3.0.0/develop branch

- .github/workflows/ic-design-system-branches.yml
Update deployment workflow to incorporate v3 branch, where v3 work is hosted separately to other branch work
Half of https://github.com/mi6/ic-ui-kit/issues/2059
> ci(root): update deployment workflow to incorporate v3 branch

- .github/workflows/release-design-system.yml
Update release step to not remove check-versions branch
N/A
> ci(root): update release step to not remove check-versions branch

- CONTRIBUTING.md
- src/content/structured/components/toggle-buttons/accessibility.mdx
- src/content/structured/components/toggle-buttons/guidance.mdx
- src/icds-pages-data.json
- Update links pointing to radio buttons component page in toggle button guidance
- Change "components/radio-buttons" to "components/radio" following a previous change to the radio buttons component page URL
- Prettier fixes in CONTRIBUTING.md
#1048
> docs(root): update links pointing to radio buttons component page in toggle button guidance

- audit-ci.json
> chore(root): update audit allowlist

- src/content/structured/components/data-table/code.mdx
- src/content/structured/components/data-table/story-data.ts
- src/data/canary-component-names.json
Add code examples for truncation (tooltip and show-hide) and text wrap in data table
#1089
> docs(root): add code examples for truncation and text wrap in data table

- src/content/structured/components/tree-view/code.mdx
- src/content/structured/components/tree-view/guidance.mdx
- src/content/structured/components/typography/guidance.mdx
- src/data/canary-component-names.json
Add tree view guidance and code examples.
The guidance is only temporary until full guidance is written #1075 
N/A
> docs(root): add tree view guidance and code examples

- src/content/structured/components/card-horizontal/guidance.mdx
Update horizontal card storybook urls
N/A
> fix(root): update horizontal card storybook urls

- audit-ci.json
- package-lock.json
> chore(root): update audit file

- src/content/structured/community/index.mdx
Added community projects to website
- [x ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)
> docs(root): added community projects to website

- gatsby-config.js
- src/components/Search/index.tsx
Update search bar to return more results when the search term is included in the page content, subtitle or title, rather than just title
#1087
> fix(root): update search bar to return more results

- src/content/structured/get-started/figma.mdx
Update Figma community link from v2.1 to v2.2
~Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.~
~- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.~
~- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)~
> Update Figma community link from v2.1 to v2.2

- src/components/Layout/index.css
Fixes footer alignment issue in chrome browser
#1166
> fix(root): fixes issue with footer alignment

- src/content/structured/components/radio/code.mdx
Corrected the react code preview mismatch
fix: corrected the radio button's conditional react code preview mismatch
#1049
> docs(root): corrected the react code preview mismatch

- src/content/structured/components/buttons/code.mdx
- src/icds-pages-data.json
Add new example for dropdown button with popover menu
#1184
> feat(root): add new example for dropdown button with popover menu

- .github/workflows/scorecards.yml
Update scorecards workflow to use v4.3.1
N/A
> chore(root): update scorecards workflow to use v4.3.1

- src/components/Search/index.tsx
Update Search index.tsx to fix errors in local build
N/A
> Fix search issues preventing local build

- package-lock.json
- src/components/SubsectionNav/index.css
- src/components/SubsectionNav/index.tsx
- src/templates/CoreTemplate/index.css
Replace left hand nav with tree view component.
Issue created for tooltip hiding behind content - https://github.com/mi6/ic-design-system/issues/1210
#1132
> feat(root): replace left hand nav with tree view component

- src/content/structured/components/data-table/code.mdx
Add sort event to sortable data table example
https://github.com/mi6/ic-design-system/issues/1056
> docs(root): add sort event to sortable data table example

- src/content/structured/community/roadmap.mdx
- src/icds-pages-data.json
The roadmap pages have been updated with new 'current focuses' and more recent releases
> 1214-update-community-roadmap-page

- src/components/TopNavWrapper/index.tsx
fix on top nav item not showing as selected
#1236
> fix(root): display correct styling on nav item

- src/components/TopNavWrapper/index.tsx
top-nav pic for selected tabs not showing styling
> fix(root): cherry-pick

- audit-ci.json
- package-lock.json
updated packages to remove vulnerabilities from audit-ci (V2 only)
> ci(root): audit fix

- src/content/structured/get-started/a-design-system.mdx
- src/content/structured/get-started/ag-grid-theme.mdx
- src/content/structured/get-started/design.mdx
- src/content/structured/get-started/development.mdx
- src/content/structured/get-started/testing-with-jest-and-rtl.mdx
- src/icds-pages-data.json
Pathway changes, prettier run
Changing pathways to re-add pages that were lost
> fix(root): added missing pages back

- package-lock.json
Update package-lock file to fix failing audit
N/A
> build(root): update package-lock to fix vulnerabilities

- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/install-components.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/releases-versioning.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
- Added web-components to ensure correct styling while in pre-release
- Added correct shell comment syntax
[#2974](https://github.com/mi6/ic-ui-kit/issues/2974)
> docs(root): added web-components to react install page

- src/content/structured/components/alerts/code.mdx
- src/content/structured/components/badge/code.mdx
- src/content/structured/components/buttons/code.mdx
- src/content/structured/components/data-list/code.mdx
- src/content/structured/components/divider/code.mdx
- src/content/structured/components/empty-state/code.mdx
- src/content/structured/components/hero/guidance.mdx
- src/content/structured/components/links/code.mdx
- src/content/structured/components/pagination/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/section-container/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/components/stepper/code.mdx
- src/content/structured/components/toasts/code.mdx
- src/content/structured/components/toggle-buttons/code.mdx
Update theme and monochrome code examples so that they're visible in both light and dark mode
#1274
> fix(root): update theme and monochrome code examples

- src/content/structured/patterns/components/StackblitzButton/index.tsx
Removed arg that had previously been removed from the function call
> fix(root): removed missing arg from function call

- src/components/AttributeCards/index.css
- src/components/AttributeTable/index.css
- src/content/structured/components/date-picker/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/get-started/ag-grid-theme.mdx
- src/content/structured/get-started/index.css
- src/icds-pages-data.json
Roll up of a few sizes for v3 site. Fixes images on cards and overflow issues with code examples on mobile devices.
#1270 - icons on cards not visible
#1271 - Ag grid theme causing horizontal scroll
#1279 - date picker examples causing horizontal scroll
> fix(root): fixes images on cards and overflow issues

- src/content/structured/components/hero/guidance.mdx
- src/content/structured/components/side-nav/guidance.mdx
- src/content/structured/components/top-nav/guidance.mdx
- src/content/structured/styles/colour.mdx
Changed references of theme to brand
#1338
> docs(root): changed theme to brand

- src/content/structured/components/toasts/code.mdx
Cherry picked v2 changes for new toast example 
#2633
> 2633 IcToast code example cherry pick

- .github/workflows/ic-design-system-v3-main.yml
- package.json
Adds deployment of v3 site when changes merged to v3.0.0/main
Site will be hosted on https://mi6.github.io/ic-design-system-githubpages/v3/
#1335
> V3 site deployment

- src/content/structured/components/select/code.mdx
Tiny correction to select code example
N/A
> fix(root): update select code example to display label prop correctly

- .github/workflows/ic-design-system-v3-main.yml
- package.json
Adds deployment of v3 site. Was previously merged into v3.0.0/develop, but need to go into v2 codebase to ensure the workflow is run.
#1335
> chore(root): v3 site deployment

- .github/workflows/check-versions-to-develop-design-system-v3.yml
- .github/workflows/release-design-system-v3.yml
Adds workflow for merging to v3 main branch and releasing the v3 site. replicates https://github.com/mi6/ic-design-system/pull/1378 in v3 branch
#1335
> cherry-pick v3 site build & release

- src/components/WrappedLink/index.tsx
- src/styles/gatsby-override.css
Cherry pick #1382 & #1383 
https://github.com/mi6/ic-ui-kit/issues/2197 & #1365
> Cherry pick 1382 & 1383

- src/components/ComponentDetails/PropTable/PropDescription/index.css
- src/content/structured/components/date-picker/code.mdx
- src/content/structured/components/footer/code.mdx
- src/data/canary-component-names.json
Fixed small issues on website:
- Colour of asterisk next to required props difficult to see in light + dark mode
- Text in "IcChange event" date picker code example difficult to see in dark mode
- A few changes to make code examples tidier and work properly in StackBlitz
- Ran prettier:fix and npm run build
N/A - thought to just open a PR as the issues are small and mostly things it would be good to fix before v3 pre-release
> fix(root): fix small issues on website

- src/content/structured/components/date-picker/code.mdx
- src/content/structured/components/footer/code.mdx
- src/data/canary-component-names.json
Small fixes to code examples, ran prettier:fix and `npm run build`
Includes similar changes to PR #1387 - this PR was done in v3 but some issues were also in v2 so wanted to implement them in v2 as well
N/A
> fix(root): tidy up footer code examples, run prettier:fix and build

- src/templates/Homepage/index.css
Fixes styling of get started link when visited
N\A
> fix(root): fixes get started link visited state styling

- src/components/Layout/index.tsx
- src/config.js
- src/templates/Homepage/index.css
- src/templates/Homepage/index.tsx
- Added banner and footer link to direct people to v3 guidance site
#1033
> feat(root): added link to v3 guidance site

- src/components/SubsectionNav/index.tsx
adds fixed strategy to truncated items along with updating the items appropriately when tree view expands and causes additional truncation
To test: 
- go to [ui-kit pr](https://github.com/mi6/ic-ui-kit/pull/3238)
- npm pack the canary components and locally install on branch 
- going to either accessibility or get started tabs and opening tree view items 
Expected behavior is items correctly truncating both on hover and keyboard  
#3171
> fix(root): allow tree items to truncate correctly

- src/styles/gatsby-override.css
stops color from overriding hero styles
> fix(root): removed overriding important flag from visited links

- .github/workflows/ic-design-system-v3-main.yml
Fixes mdx links on the v3 deployed site
N/A
> ci(root): fixes mdx links on v3 deployed site

- audit-ci.json
- package-lock.json
Updates prismjs package and adds item to allow list
N/A
> V2 audit fix

- audit-ci.json
- package-lock.json
ran audit fix and removed some vulns from audit-ci
> build(root): audit update

- audit-ci.json
- package-lock.json
updated dependencies to remove vulnerabilities
> build(root): audit update v3

- gatsby-node.js
Generate llms.txt and llms-full.txt based on markdown source to help provide AI LLMs with up-to-date context on the latest documentation.
Generate llms.txt and llms-full.txt based on the loose standard defined [here](https://llmstxt.org/) with examples from [here](https://directory.llmstxt.cloud/). This should allow scraping or adding up-to-date documentation into AI LLM contexts more easily.
> feat(gatsby-node.js): add support for llms.txt

- src/content/structured/components/select/code.mdx
Update searchable/multi select headings so that the url is made correctly, and update readonly example so it appears as readonly
#1434
> fix(root): update searchable/multi select headings, and readonly example

- src/content/structured/components/chips/code.mdx
added a switch colour code example
contributes towards #619
> fix(root): switch colour code example

- src/content/structured/components/data-table/code.mdx
Add code example for slotted pagination bar in data table
#1044
> 1044 slotted pagination example

- src/components/Layout/index.tsx
Update back to top to sit above last updated section container when it's nearing the bottom of the page
#1313
> Extra padding for back to top

- src/content/structured/components/badge/code.mdx
Added an icBadge 'customColor' example in the guidance site
> docs(root): added icBadge customColor code example

- src/content/structured/components/card-vertical/code.mdx
Added the expandable prop to the stackblitz component to match site component
> fix(root): correcting the stackblitz component

- src/content/structured/get-started/migrating-to-v3.mdx
- src/data/canary-component-names.json
Update v3 migration guide with missing breaking changes
#1446
> 1446 review v3 breaking changes documented on site

- src/config.js
- src/templates/Homepage/index.tsx
updated url and alert title to prepare for v3 stable release
#1496
> fix(root): updated v3 alert to point to updated URL

- src/components/CookieBanner/index.tsx
- src/content/structured/components/dialog/code.mdx
- src/content/structured/get-started/migrating-to-v3.mdx
- src/content/structured/get-started/releases-versioning.mdx
- src/templates/Homepage/index.tsx
- src/templates/Standard/index.tsx
- Added updated prop to breaking changes list, and created a code example with the new prop. (New prop obviously only just been merged so won't work on the link below, but its been added preemptively for next release.) https://github.com/mi6/ic-ui-kit/issues/3441
- Added alert to homepage to point people to new URL for v2. Also updated the URL in releases/versions page #1496
> Guidance site updates for v3

- audit-ci.json
Adds to allowlist for react-router audit issue
N/A
> chore(root): fixes audit failure

- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/install-components.mdx
- src/content/structured/get-started/migrating-to-v3.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
Update install instructions to remove the @next tag
#1262
> Remove next from install instructions

- src/content/structured/get-started/migrating-to-v3.mdx
Adds breaking change info for icSelect onIcChange event value
N/A
> docs(root): adds breaking change info

- src/content/structured/get-started/figma.mdx
- src/templates/Homepage/index.tsx
Updated Figma guidance to point to v3 libraries. Added section to explain separate data table library
> docs(root): updated Figma guidance to point to new libraries

- src/content/structured/components/dialog/code.mdx
Fixes javascript interactive content dialog example not working in stackblitz
N/A
> fix(root): fixes dialog example not working in stackblitz

- package-lock.json
Updates base-x package to resolve audit issue
N/A
> Update of base-x package for audit issue

- package-lock.json
Updates base-x package to resolve audit issue - cherry pick into v2
N/A
> Update of base-x package for audit issue - v2 cherry-pick

- src/content/structured/components/skeleton/code.mdx
skeleton/card code example on the site matches the stackblitz preview
> fix(root): skeleton/card code example matches preview

- src/content/structured/components/data-table/code.mdx
- Added code example for row selection within ic-data-table.
#1506
> Added Data table code example

- src/content/structured/components/search-bar/guidance.mdx
Add a couple of sentences to search bar guidance about searchMode prop
#560
> 560 guidance for search mode prop on ic search bar

- .github/workflows/ic-design-system-branches.yml
- .github/workflows/ic-design-system-main.yml
- .github/workflows/ic-design-system-v2-main.yml
- src/components/CookieBanner/cookies.helper.ts
- src/components/Layout/index.tsx
- src/config.js
- src/content/static/components/InlineCookiesManager.tsx
- src/content/structured/icds/cookies-and-storage-policy.mdx
- src/types/index.d.ts
Migrate analytics to Matomo
https://github.com/mi6/ic-design-system/issues/1546
> Migrate analytics to Matomo

- audit-ci.json
- package-lock.json
updated deps after audit fix, removed fixed vulns from audit-ci
> build(root): updated dependencies for v2

- src/content/structured/community/roadmap.mdx
Updates roadmap page with latest info
#1558
> docs(root): updates roadmap page

- src/components/Layout/index.css
- src/content/structured/components/accordion/code.mdx
- src/content/structured/components/alerts/code.mdx
- src/content/structured/components/badge/code.mdx
- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/card-horizontal/code.mdx
- src/content/structured/components/card-vertical/code.mdx
- src/content/structured/components/checkboxes/code.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/data-list/code.mdx
- src/content/structured/components/divider/code.mdx
- src/content/structured/components/empty-state/code.mdx
- src/content/structured/components/links/code.mdx
- src/content/structured/components/loading-indicators/code.mdx
- src/content/structured/components/pagination/code.mdx
- src/content/structured/components/popover-menu/code.mdx
- src/content/structured/components/radio/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/components/status-tags/code.mdx
- src/content/structured/components/stepper/code.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/theme/code.mdx
- src/content/structured/components/toggle-buttons/code.mdx
- src/content/structured/components/tree-view/code.mdx
- src/content/structured/styles/components/ColourTable/index.css
use new token in all relevant areas
> refactor(root): added new page background css token

- src/content/structured/get-started/development.mdx
- src/content/structured/get-started/install-components.mdx
- src/content/structured/get-started/migrating-to-v3.mdx
- src/content/structured/patterns/dark-mode.mdx
- src/content/structured/patterns/side-navigation-layout.mdx
- src/content/structured/patterns/top-navigation-layout.mdx
Fix broken theme links changing from custom theme page to components theme page
#1609
> fix(root): fix broken theme links

- src/content/structured/components/toggle-buttons/code.mdx
Fixes toggle button code example that wasn't working in stackblitz
N/A
> fix(root): fixes toggle button code example

- CODE_OF_CONDUCT.md
- README.md
- src/config.js
- src/content/structured/accessibility/documenting/accessibility-statements-guidance.mdx
- src/content/structured/accessibility/index.mdx
- src/content/structured/accessibility/requirement/index.mdx
- src/content/structured/accessibility/requirement/meeting-the-policy.mdx
- src/content/structured/community/index.mdx
- src/content/structured/components/data-list/code.mdx
- src/content/structured/get-started/a-design-system.mdx
- src/content/structured/get-started/index.mdx
- src/content/structured/icds/accessibility-statement.mdx
- src/content/structured/icds/privacy-policy.mdx
- static/ic-side-nav-fixed-example/index.html
Add references to HMGCC where needed, including adding HMGCC GitHub to community page
#1611
> docs(root): add references to HMGCC where needed, including adding HMGCC GitHub to community page

- package.json
- updateNavPriority.js
Add script to automatically update nav priority when new component guidance is added to the site
N/A
> Automate nav priority updating
