mi6/ic-design-system

- src/content/structured/community/contribute.mdx
- src/content/structured/community/index.mdx
- Add full stop to the end of the first paragraph on the "community" page
- Fix bad link on the "how to contribute" page by removing extra square bracket
#69
> Add missing full stop and fix bad link

- src/content/structured/get-started/releases-versioning.mdx
New page within the guidance site detailing the teams approach to releases and versioning.
#20
> docs(root): adding docs for versioning and releases

- src/components/AttributeCards/index.css
- src/components/AttributeCards/index.tsx
- src/components/CodePreview/index.css
- src/components/ComponentDetails/EventTable/index.tsx
- src/components/ComponentDetails/MethodTable/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
- src/components/ComponentDetails/SlotTable/index.tsx
- src/components/ComponentDetails/StyleTable/index.tsx
Add max width to component preview, and use attribute cards for xs breakpoint
#86
> fix(root): add max width to component preview, and use attribute cards for xs breakpoint

- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/tooltips/code.mdx
Created different component demos for left and right tooltips, and added inline to react router side nav example so that they don't overflow out of the component preview.
Issue 92 in the UI kit repo
> Overflowing tooltips and side nav

- src/components/SubsectionNav/index.tsx
Added a function to close the side nav when clicking off it on mobile devices
> feat(root): add blur handling for responsive side nav

- package-lock.json
- src/content/structured/components/page-header/guidance.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- Change page header example component to tabs variant
- Update package lock
- Add missing full stops to "Testing with Jest" page and remove "to" before finding nav items in example showing how to use the queryselector
#106
> Change example component on page header to tabs variant

- src/components/AnchorNav/index.css
- src/components/SubsectionNav/index.css
- src/content/structured/styles/components/ColourTable/index.css
Added outlines to show focus on left hand nav (including making sure outline is not cut off / hidden) and anchor nav items, made selected indicator visible on anchor nav, made colour swatches visible and added white outline when in dark mode for better contrast with background.
Selected indicator for left hand nav has been done in [GCHQ-Developer-741's PR](https://github.com/mi6/ic-design-system/pull/116/files).
#91
> feat(root): high contrast mode changes - nav components and colour page

- src/content/structured/components/alerts/code.mdx
- src/content/structured/components/back-to-top/code.mdx
- src/content/structured/components/buttons/code.mdx
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/classification-banner/code.mdx
- src/content/structured/components/hero/code.mdx
- src/content/structured/components/links/code.mdx
- src/content/structured/components/loading-indicators/code.mdx
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/search-bar/code.mdx
- src/content/structured/components/select/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/components/status-tags/code.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/text-input/code.mdx
- src/content/structured/components/tooltips/code.mdx
- src/content/structured/components/typography/code.mdx
After conversation with designers, instead of refactoring the codedetails tables to include the headers in the AnchorNav, added a Component Details header to markdown.
#25
> docs(root): added heading for componentdetails

- src/content/structured/components/page-header/code.mdx
Add missing opening breadcrumbs tag to react page header example
#124
> fix(root): add missing opening breadcrumbs tag

- .github/pull_request_template.md
Updated the pull request template to add link to the manual accessibility testing guidance and draw more attention to that PRs should be raised against the `develop` branch
[fix labelling of 'Radial indeterminate'](https://github.com/mi6/ic-design-system/pull/150)
> docs: pr template, add links and highlight use of the develop branch

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/delete-gh-pages-folder.yml
Write access is not granted when a PR is from a forked repo, so adding a condition to only run when the head branch is from the ic-design-system repo
> fix(root): fixed QA link repo to not run on forked branches

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/welcome-new-contributors.yml
Stopping workflows from triggering on forks when not needed, and when triggering on our branches when not needed
> fix(root): stopping workflows from triggering incorrectly

- src/components/ComponentDetails/SlotTable/index.tsx
Add an explanation about slots above the slots table on the code pages for the components. Had to add the 'language-text' class to the `<code>` so it displays the same grey background as other code blocks written in markdown.
#15
> feat(root): add explanation about slots to components' code pages

- src/content/structured/accessibility/needs/auditory.mdx
Fixed link that contained space and was therefore directing the user to a non-existent page in the site instead of an external page
> fix(root): fixed broken reference link on page

- src/content/structured/components/data-entity/code.mdx
- Updated data entity previews and code snippets to match those in the 'Guidance' section
- Changed hrefs on 'Edit' links in data entity to navigate to current page instead of homepage
- Added more variants of status tags to data entity
- Changed buttons in editable data entity example to match editable example in guidance section more closely (and also follow guidance on primary / secondary buttons more closely) - also set 'readonly' to empty string rather than 'true' / 'false' to follow online docs about setAttribute()
#128
> refactor(root): update and fix issues with data entity previews / examples

- .github/workflows/add-qa-link-to-issues.yml
Updated the QA link which appears in issues due to GitHub pages domain automatically changing
N/A
> fix(root): updated qa link due to gh-pages update

- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
Added guidance about adding import for normalize.css file to getting started guides.
The guidance has been copied from the guidance which was added and merged into the UI Kit repo (with very slight changes e.g. 'top level CSS file' -> 'top level index file' in the Gatsby instructions).
mi6/ic-ui-kit#296
> docs(root): add guidance about normalize.css file

- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/page-header/guidance.mdx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/stepper/code.mdx
- src/content/structured/components/stepper/guidance.mdx
Add compact stepper and hideStepInfo code examples for stepper. Prettier fix to side nav. Update props on page header
#198
> docs(root): add additional code examples for stepper

- src/components/ComponentDetails/EventTable/EventDescription/index.css
- src/components/ComponentDetails/EventTable/EventDescription/index.tsx
- src/components/ComponentDetails/EventTable/index.tsx
- src/components/ComponentDetails/PropTable/PropDescription/index.css
- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
Add deprecation descriptions and warning status tag to events and props table.
#269
> fix(root): add deprecated event descriptions back

- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/buttons/code.mdx
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/hero/code.mdx
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/stepper/guidance.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/tabs/code.mdx
- src/content/structured/components/text-input/code.mdx
- src/content/structured/components/top-nav/code.mdx
- src/content/structured/get-started/react.mdx
Add guidance for using SlottedSVG, and update React code examples using slotted SVGs to replace `<svg>` with `<SlottedSVG>`.
Also ran prettier:fix which made changes in stepper file.
#234
> docs(root): add guidance for using SlottedSVG and update code examples

- src/content/structured/get-started/test-components.mdx
- src/content/structured/get-started/testing-with-jest.mdx
- src/content/structured/get-started/testing-with-react-testing-library.mdx
Restructure get started navigation to separate out testing with overview of the shadow dom moved out of jest page to overview.
#295
> docs(root): restructure get started navigation to separate out testing

- src/components/CodePreview/index.tsx
- src/content/structured/components/hero/code.mdx
Using TSX as the highlighter language was causing issues with certain closing tags. Escaping the characters did not have the desired effect. The language prop is now set to JSX which uses the same theme and fixes the closing tag issue.
#85
> docs(root): updated prism highlighter to use jsx instead of tsx

- package-lock.json
Merging dependabot PRs breaks the linting within the CI. Manually running npm audit fix updates the same packages but does not break linting. This PR includes the manually updated packages
Updated packages which were highlighted by dependabot: 
- https-cache-semantics: https://github.com/mi6/ic-design-system/compare/develop...chore/update-dependencies#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R15299 // related PR: https://github.com/mi6/ic-design-system/pull/306
- ua-parser-js: https://github.com/mi6/ic-design-system/compare/develop...chore/update-dependencies#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R27446 // related PR: https://github.com/mi6/ic-design-system/pull/250
N/A
> chore(root): update vulnerable packages

- src/content/structured/components/tabs/code.mdx
Added an example of the compact variant of 'IcTab'
#176
> Add example of compact Tabs to Code page

- .github/workflows/ic-design-system-branches.yml
Concurrency action has been moved from the deployment step to the overall action. This will make sure the latest codebase of the branch is being built. As part of the investigation, there was a requirement to update the concurrency property on `pages-build-deployment` action provided by GitHub Pages by default but it is not accessible.
#6
> [github-action]: Bugfix/6 concurrency update

- src/content/structured/components/chips/code.mdx
- static/ic-side-nav-fixed-example/index.html
After removing normalize from the core CSS, an additional stylesheet ref was required in the side nav example
N/A
> fix(root): updated side nav example

- src/content/structured/components/cards/code.mdx
- src/content/structured/components/cards/guidance.mdx
PX changed to '%' and a max width/height added to image. To test the changes;
- Navigate to card component
- Change to mobile view in inspect
- Shrink screen to see image shrink and maintain aspect ratio
Please note that in the guidance section the overlay will still pop out, this is due to the buttons causing the same issue. Navigate to the code examples and see 'top-image' and 'mid-image' variants to view the fix properly.
#294
> fix(root): fix image in card causing overlay on mobile

- src/components/TopNavWrapper/index.tsx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/top-nav/code.mdx
Update ICDS app title to use gatsby link, and add update code examples for top nav and side nav to show slotted app title link examples in existing React Router examples.
Needs to wait for the latest ui-kit component changes, so will have to be merged after the packages are updated for complete confidence it all works. Or to test locally, run npm pack. **Ideally this needs to be merged before we do the next develop -> main** so that developers have examples of how to use slotted app title links as the functionality will be available for them. 
When viewed with the latest changes there appears to be a bug in the side nav, but [a separate ticket has been raised](https://github.com/mi6/ic-ui-kit/issues/444) for that in the ui-kit. 
#293
> feat(root): update ICDS app title to use gatsby link, and add update code examples

- src/components/AnchorNav/index.css
- src/components/CodePreview/index.css
- src/components/DoDontCaution/index.css
- src/components/Header/index.css
- src/components/Layout/index.css
- src/components/Metadata/index.css
- src/components/Permalink/index.css
- src/components/SubsectionNav/index.css
- src/components/WrappedCode/index.css
- src/content/structured/patterns/components/ErrorSummaryEx/index.css
- src/content/structured/styles/components/ColourTable/index.css
- src/content/structured/styles/components/IconFinder/index.css
- src/content/structured/styles/components/TypographicScale/index.css
- src/pages/404.css
- src/templates/CoreTemplate/index.css
- src/templates/Homepage/index.css
- src/templates/Standard/index.css
PX values changed to REM excluding screen sizes, @media, 1px borders and gatsby-reset.css
#217
> PX -> REM on guidance site

- src/components/Header/index.tsx
Sets sticky-desktop-only prop to fix page header on larger viewports
#168
> fix(root): turns on sticky page header for desktop

- package-lock.json
Audit fix updated minor version for webpack and a patch for Gatsby
Manually running `audit fix` is required due to dependabot causing linting issues: https://github.com/mi6/ic-design-system/pull/339
N/A
> build(root): updated webpack version after audit fix command

- audit-ci.json
- src/content/structured/styles/elevation.mdx
- src/styles/gatsby-reset.css
Adds the z-index tokens and descriptions of use to the elevation page.
#313
> Add z-index tokens and guidance to elevation page

- src/components/CodePreview/index.css
Fixes some components in preview overlapping the sticky page header on scroll. Affected components were:
ic-page-header
ic-side-navigation
ic-classification-banner
N/A
> fix(root): fix content overlapping page header

- src/styles/gatsby-reset.css
Ticket requests that elevation page z index tokens be consistent with colour tokens. 
Removing the css styling allows consistency with minimal code disruption, but unsure if this is acceptable. 
If ic-typography is required in the mdx, happy to change this and work on the ticket further.
#385
> fix(root): removed font size and weight from css-token

- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/cards/code.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/data-entity/code.mdx
- src/content/structured/components/footer/code.mdx
- src/content/structured/components/hero/code.mdx
- src/content/structured/components/page-header/code.mdx
- src/content/structured/components/switch/code.mdx
- src/content/structured/components/tabs/code.mdx
- src/content/structured/components/text-input/code.mdx
- src/content/structured/components/top-nav/code.mdx
removed abbreviated SlottedSVG and svg from code snippets in components pages. Added functioning code so user can copy working code and not have to manipulate it to make it function
> 320 update slotted svg code snippets

- src/content/structured/components/breadcrumbs/code.mdx
- src/content/structured/components/breadcrumbs/guidance.mdx
- src/content/structured/components/select/code.mdx
- src/content/structured/components/skeleton/code.mdx
- src/content/structured/components/text-input/code.mdx
Corrected small typos in code examples stated on issue #252 and following small changes were made:
- In the react example of breadcrumbs, the second breadcrumb href has an extra space, removed extra spaces to fix the issue
- Skeleton contains height="20" but height doesn't exist, removed height from react example IcSkeleton
- Textfield example comes with maxLength="25" but a string isn't assignable to a number so it would only accept maxLength={25} - changed maxLength="25" to {25}
- The Select react example has const [value, setValue] = useState(null); however in typescript projects where is needed, null causes errors. Updated typescript code with: const [value, setValue] = useState("");
- The prop rows on the react component IcTextField is a number type. The react examples with the prop …
> fix(root): updated and fixed small typos on code examples

- src/content/structured/components/classification-banner/accessibility.mdx
- src/content/structured/components/classification-banner/code.mdx
- src/content/structured/components/classification-banner/guidance.mdx
Removed ic-classification-banner that was causing issues in the guidance
#543
> 543 classification banner on classification banner page overlays on footer content

- src/content/structured/components/top-nav/code.mdx
- src/content/structured/components/top-nav/guidance.mdx
removed nav item from top nav code preview to prevent flickering on certain screen sizes
The flickering identified on the guidance site is caused by the scroll buttons appearing and changing the size of the navigation, which triggers an infinite loop in the resize observer. The changing size stretches the top navigation component in the code preview, which shouldn't be the case.
Because the top navigation will never be used in this way in the real world, the fix for the moment is to remove one of the nav items that triggers the overflow and raise another ticket to investigate this behaviour.
#425
> fix(root): removed nav item from example

- src/content/structured/get-started/a-design-system.mdx
Correct duplicate pronouns typo, presumed _it_, but it could be _we_ as well.
> fix(docs): correct duplicate pronouns typo

- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
Update prop description cell to not show description/type if prop is deprecated. There was previously a gap where description would've been had the prop not been deprecated.
#467
> fix(root): update prop description cell to not show details if deprecated

- src/content/structured/components/tooltips/code.mdx
fixed example as the wrong tooltip was being targeted and therefore the method wasn't displaying in the preview
> fix(root): fixed example of new tooltip method

- src/components/AnchorNav/index.css
- src/components/AnchorNav/index.tsx
Remove div around `<li>` so that it passes accessibility checks as div is not a valid child of a `<ul>`
#405
> fix(root): remove div around <li> so that it passes accessibility checks

- src/content/structured/components/top-nav/code.mdx
The app-title and navigation button icon was not appearing for the component demo in ic-top-navigation code tab. This has been fixed with the additional SlottedSVG import.
N/A
> fix(root): added slottedsvg import for top-navigation

- .github/workflows/ic-design-system-branches.yml
Added push trigger on develop for github action as develop build should display the latest code and not have to be manually triggered.
Also added additional step to extract branch name due to ref_name returning <ticket_number>/merge if PR triggers build
N/A
> fix(root): added push trigger on develop branch for github action

- src/content/structured/styles/components/ColourTable/index.css
- src/content/structured/styles/elevation.mdx
- src/styles/gatsby-reset.css
- src/utils/helpers.ts
adjusted table css to not go off screen on mobile devices. also fixed lint warning
Added media queries to the HTML table css and colour table css to reduce the space taken by the table cells on smaller devices. This prevents other page content from stretching off the page on mobile.
#401
> fix(root): fixed table width issues on mobile

- src/config.js
- src/content/structured/icds/accessibility-statement.mdx
- src/content/structured/icds/index.mdx
Updated the url of the Accessibility Statement from /icds/ to /icds/accessibility-statement
Required fix was to move Accessibility Statement from /icds/ to /icds/accessibility-statement
However, to do this I also had to write a parent page so accessibility-statement, cookies-policy and privacy-policy would show side-navigation. Please check the wording on this new page :) 
> refactor(root): update url for accessibility statement

- .husky/email-check.sh
- .husky/pre-commit
- CONTRIBUTING.md
Added a email checking script to husky precommit hook that enforces git email to be set to github user email address. Added guidance to contributing.md
#584
> chore(root): enforce github user email in precommit

- src/content/structured/community/contribute.mdx
adds links to UI-Kit repo and issues board, where previously links only pointed to Design System
#352
> docs(docs): adds ui-kit links on contribution page

- src/components/CodePreview/index.tsx
- src/content/structured/components/buttons/code.mdx
Update copy code button to use left-icon slot and update button docs
> fix(root): update copy code button to use left-icon slot

- gatsby-browser.js
- gatsby-node.js
- gatsby-overrides.js
- gatsby-ssr.js
- src/components/AnchorNav/index.tsx
- src/components/AttributeCards/index.tsx
- src/components/Header/index.tsx
- src/components/Layout/index.tsx
- src/components/SubsectionNav/index.tsx
- src/content/structured/components/dialog/guidance.mdx
- src/sharedTypes.tsx
- src/templates/CoreTemplate/index.tsx
- src/templates/Standard/index.tsx
Removed previous code that involved updating the tab content manually on component pages, so that they now function using Gatsby Links to preserve the url and Anchor Nav behaviour.
Added some additional code to focus the clicked tab when moving between the code, guidance and accessibility content, to preserve position on the page for keyboard users
#563
> fix(root): changed tab behaviour on component pages

- src/content/structured/components/cards/code.mdx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/top-nav/code.mdx
Update cards, side navigation and top navigation code examples to show how to use the badge slot.
Will need to build locally to test until the next release.
#638
> docs(root): update cards, side navigation and top navigation code examples

- src/components/CodePreview/index.tsx
- src/components/ComponentDetails/EventTable/index.tsx
- src/components/ComponentDetails/MethodTable/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
- src/components/ComponentDetails/SlotTable/index.tsx
- src/components/ComponentDetails/StyleTable/index.tsx
- src/components/WrappedH1/index.tsx
- src/components/WrappedH2/index.tsx
- src/components/WrappedH3/index.tsx
- src/components/WrappedH4/index.tsx
Update wrapped typography to use logical heading structure, so that top level headings on page content are h3 instead of h4 etc.
#611
> fix(root): update wrapped typography to use logical heading structure

- .eslintrc.js
- src/components/CodePreview/index.tsx
- src/content/structured/components/dialog/code.mdx
- src/templates/CoreTemplate/index.tsx
Removed confirming tooltip from copy code button and replaced with auto-dismissing toast. This should announce to screen reader's when code has been copied
#613
> fix(root): changed conformation of copying code snippet

- src/content/structured/components/badge/code.mdx
Updates toggle for show/hide badge to be idomatic to React in both snippet and implementation
Popover and Dialog are addressed in other tickets
#677
> Update badge toggle snippet implementation

- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/testing-with-jest.mdx
Move testing with jest information from react to testing file so that all testing with jest information is in the same place
#656
> chore(root): move testing with jest information from react to testing file

- src/components/TopNavWrapper/index.tsx
- src/content/structured/components/top-nav/code.mdx
Update top nav to use short-app-title slot and app-icon to slot a link in order to correctly route around the site. Added guidance to the top nav code page to show users how to do this too.
Will need to be built locally until https://github.com/mi6/ic-ui-kit/pull/1282 is in main.
#693
> fix(root): update top nav to use short-app-title slot and app-icon to slot a link

- src/components/Metadata/index.tsx
- src/content/structured/components/alerts/code.mdx
Remove inline prop for icLink on alerts code page as there is no inline prop on icLink.
Also a small prettier change.
> docs(root): remove inline prop for icLink on alerts code page

- audit-ci.json
- gatsby-overrides.js
Update export of RouteAnnouncerProps so it can be accessed by gatsby and apply `display: "none"` instead of showing below footer
#657
> fix(root): update export of RouteAnnouncerProps so it can be accessed by gatsby

- src/content/structured/get-started/custom-theme.mdx
- src/content/structured/get-started/nextjs.mdx
- src/content/structured/get-started/react.mdx
Update get started guides to have a page of next.js, this includes explaining the limitations with web components and moving the existing information about transpiling the react package.
#749
> docs(root): update get started guides to have a page of next.js

- src/components/AnchorNav/index.tsx
- src/components/Header/index.tsx
- src/components/SubsectionNav/index.tsx
- src/templates/CoreTemplate/index.tsx
Updated accessible labels for the left hand nav and anchor nav to be more descriptive regarding what a user is focused on, giving them more information
#610
> fix(root): updated accesible labels for anchor and left hand navs

- src/components/AnchorNav/index.tsx
Ensured that AnchorNav returns null rather than false when now headings are provided
> fix(root): changed return type of AnchorNav

- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
Removed the lone lines of text indicating version at the top of Get Started -> Angular/Svelte/Vue, and placed information into IcAlert components for increased cohesion on the page. 
#730
> 730 add information alert to angular page

- src/content/structured/get-started/custom-theme.mdx
Added sentence to update guidance about using CSS variables to set the theme colour, making it clearer that you need to use the three separate variables as shown. (From a conversation with a customer, it seems there may have been some confusion about this method).
Also updated sentence about focus indicators changing as it no longer happens since we use the same focus indicator for everything.
> Updates to colour theme guidance

- src/content/structured/components/popover-menu/code.mdx
- src/content/structured/components/popover-menu/guidance.mdx
These changes fix the issues on the guidance site with the open and closed state for the IcPopoverMenu.
#807
> fix(root): fix the popover open and close state

- src/components/ComponentGallery/index.tsx
- src/templates/Homepage/index.tsx
Update cards to use h4 element as slotted heading with aria label to fix lack of pause for screen readers.
#607 
#718
> fix(root): update cards to use h4 element as slotted heading

- src/content/structured/styles/components/ColourTable/colours.config.ts
Update colour toxen to have # so that it appears correctly with the colour circle like the others.
> fix(root): update colour toxen to have # so that it appears correctly

- src/components/Layout/index.tsx
- src/components/TopNavWrapper/index.tsx
Fixed a few errors which I noticed were being picked up when running the Accessibility Insights FastPass tool and WAVE plug-in.
- Updated ICDS logo `aria-labelledby` usage.
- Added `aria-hidden` to footer logos. These can be hidden and don't need `aria-labelledby` because they are just used to visually represent the links, and the text in the spans (describing the links) were already being read out.
- Added full stops to "SIS" to make it clearer for screen reader users, being read out as separate letters rather than "sis".
WAVE also mentions another error about cards on the home page not having discernible text but I think this is a shadow DOM issue. I have checked with VoiceOver and they get read out fine.
(N/A)
> fix(root): fix errors picked up by A11y Insights FastPass and WAVE tool

- src/content/structured/get-started/releases-versioning.mdx
Add canary component guidance to versioning page
#729
> docs(root): add canary component guidance

- src/content/structured/components/page-header/code.mdx
Code example added in for changing slots within the page header, changing the typography of a page header semantically.
#632
> feat(root): add code examples for page header using slots

- src/content/structured/components/chips/accessibility.mdx
- src/content/structured/components/chips/code.mdx
- src/content/structured/components/chips/guidance.mdx
Update IcChip guidance and examples to have aria-labels 
#1560
> docs(root): add accessible labels to chip icons

- gatsby-config.js
- package-lock.json
- package.json
Add Gatsby plugin ([gatsby-plugin-fix-fouc](https://www.npmjs.com/package/gatsby-plugin-fix-fouc)) which helps with the FOUC issue (which happens when you first load the page or refresh).
As stated in the docs, the plugin adds styling to the <body> element that hides the page until the initial render of the app is done on the client.
-----
Despite having read a lot of documentation online, I was having difficulty working out what changes I could make to the badge component itself to improve the flashing, and I know that this is just hiding the issue (and other FOUC issues) rather than actually fixing it but it at least makes things a bit better!
mi6/ic-ui-kit#1216
> fix(root): add gatsby plugin which improves flash of unstyled content issue

- src/components/AnchorNav/index.tsx
- src/components/WrappedH2/index.css
Add scroll margin to navigation headings to ensure heading doesn't hide behind the page header when anchor nav link is clicked
#728
> fix(root): add scroll margin to navigation headings

- src/content/structured/components/toggle-buttons/code.mdx
Fixed typo 's' in toggle button component preview
- [X ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)
> 875 typo in toggle button component preview

- src/components/ComponentGallery/index.css
Remove negative margin around heading on component gallery cards
#827
> fix(root): remove negative margin around heading on component gallery cards

- src/components/ComponentGallery/index.tsx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/react.mdx
Add alert to react and gatsby installation pages to advise locking web components package if they lock react package.
Also ran prettier:fix which has caused formatting changes to component gallery.
https://github.com/mi6/ic-ui-kit/issues/1089
> docs(root): add alert to react and gatsby installation pages

- .github/workflows/check-versions-to-develop-design-system.yml
- .github/workflows/ic-design-system-branches.yml
- .github/workflows/ic-design-system-main.yml
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
Added overrides to packages whose peer dependencies are out of date to ours, allowing us to stop using the `--legacy-peer-deps` flag
#923
> build(root): added peer dependency overrides to gatsby plugins

- src/components/CookieBanner/cookies.helper.ts
- src/components/CookieBanner/index.tsx
Added slash at beginning of manage cookies link to ensure it directs based of the root url rather than the current url
#789
> fix(root): added missing slash to cookie banner link

- gatsby-config.js
- package-lock.json
- package.json
- src/components/DoDontCaution/index.tsx
Imports and uses `gatsby-plugin-image` lib and the `GatsbyImage` (dynamic image) component within the `DoDontCaution` class to replace (suitable) `<img>` with `<GatsbyImage>`. Uses the `gatsby-source-filesystem` to source all the jpgs/pngs within `src` and `static`, which are then queried into `gatsbyImageData` object format with GraphQL and used within `<GatsbyImage>`. Around 10% of the images on the site aren't compatible with this due to this [Gatsby Optimisation](https://www.gatsbyjs.com/docs/how-to/images-and-media/importing-assets-into-files/#importing-assets-with-webpack), which converts the file path into a data URI, so will revert back to use of `<img>` in this case.
#726
> fix(root): implementation of gatsby-plugin-image and GatsbyImage

- src/components/DoDontCaution/index.css
The `GatsbyImage` components were forcing the status icons behind the component example image, like below:
This fix just sets `z-index: 1` on the `.do-dont-caution-containers` css class to make the icon visible again, like below:
No ticket just a fix
> Place status icons in front of GatsbyImage

- src/content/structured/components/top-nav/code.mdx
Added new code examples to top nav to show off:
- Conditionally rendering tabs #910 
- Using GatsbyLinks https://github.com/mi6/ic-ui-kit/issues/1244
Accompanies an ic-ui-kit PR aiming to bring ic-top-navigation in line with the PR checklist (https://github.com/mi6/ic-ui-kit/pull/1872)
> feat(root): added new code examples to top nav code page

- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
Add type name to component prop table
#982
> docs(root): add type name to component prop table

- src/content/structured/components/multi-select/code.mdx
- src/content/structured/components/multi-select/guidance.mdx
- src/icds-pages-data.json
Add hyphen between Multi and select, due to consistency in naming conventions of the component.
In our Storybook build and elsewhere we have the component 'Multi-select' with a hyphen. On the guidance pages this is not reflected and should be changed.
> add hyphen for Multi-select on site 

- src/content/structured/components/buttons/code.mdx
- src/content/structured/get-started/testing-with-react-testing-library.mdx
Added code examples to button page around using tooltips correctly
#667
> docs(root): added button guidance around tooltips

- src/content/structured/accessibility/needs/visual.mdx
- src/content/structured/components/switch/guidance.mdx
- Fixed typo on switch page
- Fixed contrast compliance typo from 4:5:1 to 4.5:1
> docs(root): addressed typos in switch and colour contrast

- src/components/CodePreview/index.css
- src/components/CodePreview/index.tsx
- src/components/CodePreview/types.ts
moved code action buttons from bottom of code preview and rearranged to match design on ticket
#938
> refactor(root): modified code preview component

- CONTRIBUTING.md
- src/content/structured/get-started/nextjs.mdx
The current documentation reads in a way that doesn't account for nextJS versions later than 13. 
Fixed broken link to code of conduct
n/a
> docs: update Next.js documentation to reflect new versions, fix broken link to code of conduct

- src/content/structured/components/radio/code.mdx
Added the code snippet that was missing the relevent prop shown in the example.
Issue #1050
> fix(root): add missing prop to code examples

- src/content/structured/components/card-horizontal/guidance.mdx
See https://design.sis.gov.uk/components/horizontal-card
If you click either the web component or react storybook links you get sent to a 404.
I browsed the sidepanel and found the correct URL
~- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.~
> docs: Fix typo on horizontal card url

- src/content/structured/styles/colour.mdx
- src/content/structured/styles/components/ColourTable/colours.config.ts
Removed --ic-hyperlink-hover from colour palette
On the colour palette page, the --ic-hyperlink-hover has been removed. Also removed an unnecessary sentence in the Links section regarding contrast.
#1019
> docs(root): removed --ic-hyperlink-hover from colour palette

- src/components/CodePreview/index.tsx
- src/components/CodePreview/types.ts
**Title:**
fix(root): fix syntax highlighting in code preview
**Description:**
- Added conditional language for the `<Highlight>` component.
**Files Changed:**
1. [src/components/CodePreview/index.tsx](https://github.com/mi6/ic-design-system/blob/b0fc079b9f11fc12314a2b8f31440f14fab720c6/src/components/CodePreview/index.tsx)
- Adjusted the `CodeWindow` component to accept a `language` prop and conditionally set the language for the syntax highlighting.
- Added the `language` prop to the `ComponentPreview` component.
2. [src/components/CodePreview/types.ts](https://github.com/mi6/ic-design-system/blob/b0fc079b9f11fc12314a2b8f31440f14fab720c6/src/components/CodePreview/types.ts)
- Added `language` to `CodeWindowProps` interface.
This pull request aims to fix the syntax highlighting in the …
> fix(root): fix syntax highlighting in code preview

- src/content/structured/components/badge/code.mdx
- src/content/structured/components/date-picker/code.mdx
- src/content/structured/components/status-tags/code.mdx
- src/content/structured/components/toggle-buttons/code.mdx
Updated the size prop from default to medium in badge, toggle button, date picker and status tag examples.
#1090
> docs(root): replace examples of the default size prop with medium

- src/content/structured/components/popover-menu/code.mdx
Improve react code snippets by switching to a more common solution with the react state hook instead of the react ref hook
fix #1086
Update the react code snippets and the preview component to use more common react approach
1086
> refactor(root): improve react code snippets

- src/components/CodePreview/index.tsx
fix website crashing when selecting react on a component preview that only has the react option
fix #1173
Catch null edge case where there is only one snippet
#1173
> fix(root): fix website crashing when selecting react on component preview

- src/content/structured/components/alerts/code.mdx
Add guidance for neutral alert and show default icon prop.
Issue #1126
> docs(root): add guidance for neutral alert and show default icon prop

- gatsby-browser.js
- src/components/AnchorNav/index.css
- src/styles/color-mode.css
Added a color-mode.css file to the website. Added colour tokens for light and dark mode of the table of contents / anchor nav component.
I have only added theme changes / code for the table of contents - I believe the rest (e.g. wrapping the whole website in an ic-theme component? Etc.) will be done in #1133.
-----
To view the changes in this PR, add the following to the styles in Chrome DevTools:
```
:root {
color-scheme: light dark;
}
```
and then click on the paintbrush icon to change between modes.
Part of mi6/ic-ui-kit#1214
> feat(root): add colour tokens for table of contents light and dark mode

- src/templates/Standard/index.css
When the subsection nav is sticky, it affects z-indexes further down the tree, so have added an appropriate z-index to the nav to make other floating elements appear over text.
#1210
> fix(root): added z-index to sticky subsection nav

- src/content/structured/components/popover-menu/code.mdx
- src/content/structured/components/popover-menu/guidance.mdx
Added aria-expanded to popover-menu examples.
#1064
> docs(root): add aria-expanded to popover-menu examples

- src/components/SubsectionNav/index.css
- src/components/SubsectionNav/index.tsx
- src/templates/Standard/index.css
(Updated PR description)
Fixed bugs mentioned in #1215 plus a couple of other small things I noticed. In summary this PR fixes the following:
- The scroll bar always being visible on the tree view on every page even when not needed (e.g. when all items were already visible on screen)
- The height of the tree view not filling the whole page when you first go to a new page
- A left box shadow visible on the page header
- The tree view being very tall on small screens
--------
So it's clear what has been fixed, here is a screenshot in which the first three of the above bugs are visible:
Video showing the tree view on a small screen issue:
https://github.com/user-attachments/assets/750f4581-10b8-4349-8d78-8cf233e67967
#1215
> fix(root): change overflow-y on tree view to hide permanent scroll bar

- src/content/structured/components/multi-select/code.mdx
Added the options array in the multi-select component code examples to fix the issue where the options array was not defined, causing errors when using the component.
Fixes issue #1198
> fix(root): add options array to code example

- src/components/SubsectionNav/index.tsx
- src/content/structured/get-started/install-components.mdx
- src/templates/CoreTemplate/index.css
Fixes alert on getting started page and page header disappearing
N/A
> fix(root): fixes issues spotted on v3 site

- src/components/CodePreview/index.tsx
- src/content/structured/patterns/components/StackBlitzButtonTestApp/index.tsx
- src/content/structured/patterns/components/StackblitzButton/index.tsx
Swap theme colour for code preview buttons now that they've been swapped in the ui kit
N/A
> fix(root): swap theme colour for code preview buttons

- src/components/SubsectionNav/index.tsx
Changed how the expanded prop was being applied on tree view items to fix collapsing on scroll issue. Also updated package-lock file to remove vulnerabilities.
The expanded prop now gets conditionally applied - if the current page is a child page, the prop is applied, and if not, it doesn't get applied at all (instead of just being set to false like it was previously). (The collapsing on scroll was because of updating the `navHeight` state in the `useEffect` and the [expanded prop then changing to `false`](https://github.com/mi6/ic-design-system/blob/1446feb5c495361a6be231fdb5242f7f32fe3dc0/src/components/SubsectionNav/index.tsx#L159)).
#1256
> fix(root): update expanded prop behaviour on tree view

- src/components/ComponentTesting/index.tsx
- src/components/Layout/index.tsx
- src/components/TopNavWrapper/index.tsx
- src/content/structured/accessibility/coding/css.mdx
- src/content/structured/accessibility/coding/doctype.mdx
- src/content/structured/accessibility/coding/document-structure.mdx
- src/content/structured/accessibility/coding/semantic-html.mdx
- src/content/structured/accessibility/documenting/accessibility-statements.mdx
- src/content/structured/accessibility/testing/automated-testing-limitation.mdx
- src/content/structured/accessibility/testing/automated-testing.mdx
- src/content/structured/accessibility/testing/manual-testing.mdx
- src/content/structured/get-started/development.mdx
- src/content/structured/get-started/figma.mdx
- src/content/structured/get-started/install-components.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/testing-with-jest-and-rtl.mdx
- src/context/ThemeContext.tsx
- src/templates/Homepage/index.tsx
- Removed inline styling of certain `<code>` tags, swapping it for the `language-text` class which would apply dark mode styling in line with other code snippets. #1268 
- Updated certain links in markdown that weren't using GatsbyLink, swapping them to `<a>` tags so that they utilised GatsbyLink through the WrappedLink component. https://github.com/mi6/ic-ui-kit/issues/2893
- Swapped the theme on component testing buttons to match the other component preview buttons. #1257 
- Removed `oppositeTheme` from the ThemeContext as it was no longer being used after swapping the theme.
> 1268 dm text highlighting

- src/components/CodePreview/index.tsx
feat(root): persist user's chosen language and framework for code demos
added local storage to store the stage of language and framework, to preent users from repeating the selection of their language and framework
#817
> feat(root): persist user's chosen language and framework for code demos

- src/components/Permalink/index.css
- src/components/Permalink/index.tsx
Updated permalink to prevent link appearing on its own line and causing large gap between the heading and main text.
#1160
> fix(root): updating permalink to prevent link appearing on its own line

- src/components/DoDontCaution/index.css
Reducing margin-bottom of dodontcaution so that gap between dodontcaution and heading is not too large.
#1159
> fix(root): reducing margin-bottom of dodontcaution

- src/content/structured/components/breadcrumbs/accessibility.mdx
- src/content/structured/components/breadcrumbs/code.mdx
Add note about not using slotted links in current page breadcrumbs. Relates to findings from PR [#3050](https://github.com/mi6/ic-ui-kit/pull/3050).
mi6/ic-ui-kit#2194
> docs(root): add guidance about using slotted links in breadcrumbs

- src/content/structured/patterns/components/StackblitzButton/stackblitz-helpers.ts
The `package.json` that is created for a stackblitz demo now installs web-components regardless of file format. Previously `.jsx` would load without some styling, check IcTopNavigation `Grouped links` StackBlitz to see this.
> fix(root): changes to stackblitz package json injection

- src/components/AnchorNav/index.tsx
- src/content/static/components/InlineCookiesManager.tsx
- src/content/structured/components/switch/code.mdx
- src/templates/CoreTemplate/index.tsx
- Removed any references to showState, in docs and in our own code
- Prettier fixes
[#2733](https://github.com/mi6/ic-ui-kit/issues/2733)
> docs(root): removed showState examples for IcSwitch

- src/components/WrappedLink/index.tsx
Update WrappedLink to remove the duplicated GATSBY_ICDS_PREFIX for github pages deployment
#1365
> 1365 links in markdown pages do not work on deployed site

- src/styles/gatsby-override.css
Adds a color to visited anchor tag elements in mdx.
https://github.com/mi6/ic-ui-kit/issues/2197
> fix(root): add color to visited links in safari

- src/content/structured/components/text-field/code.mdx
Add examples of custom and full width code snippets in ic-text-field
1084
Added examples of custom and full width code snippets in ic-text-field
> docs(root): add examples of custom and full width code snippets in ic-text-field

- src/content/structured/patterns/components/StackblitzButton/stackblitz-helpers.ts
Fixes web-components examples not working in stackblitz on v3 due to loading v2 packages
#1424
> fix(root): fixes web-comps stackblitz examples

- src/components/WrappedH1/index.tsx
- src/components/WrappedH2/index.tsx
- src/components/WrappedH3/index.tsx
- src/components/WrappedH4/index.tsx
- src/content/structured/components/typography/code.mdx
- Added a boolean prop called `preview` to the header tags included within the typography code previews. When mdxjs detects it and tries to replace it as per our custom component overrides, the prop is detected and a regular header tag is rendered instead. I figured that we'd still want to show the code examples as they are, since it follows our guidance to use correct header semantics, so I implemented this rather than just removing the header tags from the examples.
- Updated code snippets to read better
#1391
> fix(root): added override to mdxjs replacing typography examples

- src/content/structured/styles/components/TypographicScale/index.css
- src/content/structured/styles/components/TypographicScale/index.tsx
- src/content/structured/styles/components/TypographicScale/typography.config.ts
- src/content/structured/styles/typography.mdx
- Refactored the TypographyScale component to pull values from a config file (similar to the colours pages) rather than using hard-coded values.
- Updated the values in the new config to be the latest typography values, displayed in correct units (rem).
#1291
> docs(root): updated typography page with latest font details

- src/components/SubsectionNav/index.tsx
Update parent tree items to be collapsible when a child tree item is selected
#1407
> 1407 parent tree items should close when child tree item selected 

- src/content/structured/get-started/migrating-to-v3.mdx
Update codemod instructions to include "@next" in the npx command so that it always uses the latest version. Prevents it running the oldest version which does not have some changes e.g. it does not run on all files that need changing.
I have tested this by comparing running the npx command with vs. without "@next" on a repo with v2 ICDS components.
(Equivalent to PR [#3356](https://github.com/mi6/ic-ui-kit/pull/3356))
mi6/ic-ui-kit#3297
> docs(root): update codemod instructions to include "next" tag

- src/content/structured/get-started/migrating-to-v3.mdx
docs(root): update migrating to v3 page with Ic-Dialog and Ic-Select changes
#1436
> docs(root): update migrating to v3 page with Ic-Dialog and Ic-Select changes

- src/content/structured/patterns/components/StackblitzButton/stackblitz-helpers.ts
Fixes issue where styling was not applied to canary-react examples
#1459
> fix(root): fixes issues with canary-react stackblitz examples

- src/content/structured/components/data-table/code.mdx
- src/content/structured/components/data-table/story-data.ts
- src/data/canary-component-names.json
add examples for column widths, cell descriptions and icons, and missing cell data
New code examples added for data table. See [develop pr](https://github.com/mi6/ic-design-system/pull/1464)
#1054
> feat(root): add new data table code examples to site

- src/content/structured/styles/colour.mdx
- src/content/structured/styles/components/ColourTable/colours.config.ts
- src/content/structured/styles/components/ColourTable/index.css
- src/content/structured/styles/components/ColourTable/index.tsx
- Refactored the `colours.config.ts` file to have each colour take its respective css token, rather than manually setting hex codes, so that as changes are made to the ui-kit it will update the colours page automatically.
- Updated the layout of the `ColorTable` to display each colour's token next to the swatch, rather than the hex code. Also removed the "global token" reference in place of the individual tokens, as not every colour has one.
Some of the colours are not reflected on the page as they are waiting for the next release and on [other PRs](https://github.com/mi6/ic-ui-kit/pull/3410) and [issues](https://github.com/mi6/ic-ui-kit/issues/3363). However, the token name should indicate that it will pull through the correct value when displayed after the release.
#1461
> feat(root): updated colours page to always display latest colours

- src/components/Layout/index.css
- src/components/Layout/index.tsx
Implemented icon only variant of back to top for smaller viewports.
#959
> fix(root): implement icon variant of back to top at small screen sizes

- src/components/SubsectionNav/index.tsx
Updated the tree view on the website to not collapse when a second level / grandchild item is selected.
Also fixed some other small issues I noticed:
- Expanding a parent tree item which is a child caused its parent to collapse
- Using Enter to expand parent tree items wasn't working
- You couldn't use Space to expand or select tree items
- Wasn't possible to select the first tree item in the tree view using the keyboard ([#1478](https://github.com/mi6/ic-design-system/issues/1478))
There is still an issue where using Space to select items causes the whole page to scroll. This is a component issue, captured in mi6/ic-ui-kit#3152 (comment added to ticket).
#1471 and #1478
> fix(root): fix issue with tree view collapsing with second level item click

- src/content/structured/get-started/angular.mdx
- src/content/structured/get-started/gatsby.mdx
- src/content/structured/get-started/install-components.mdx
- src/content/structured/get-started/nextjs.mdx
- src/content/structured/get-started/react.mdx
- src/content/structured/get-started/releases-versioning.mdx
- src/content/structured/get-started/svelte.mdx
- src/content/structured/get-started/vue.mdx
- src/content/structured/get-started/web-components.mdx
update all instructions for installing components to target v2
#1495
> update install instructions to use v2 latest

- src/content/structured/components/card-vertical/code.mdx
- src/content/structured/components/card-vertical/guidance.mdx
Remove slot="icon" from ic-card-vertical interaction button svgs as this has been removed in v3
#1575
> 1575 fix card interaction button

- src/content/structured/components/data-list/code.mdx
Add code example for new data list css prop to control the label width.
This won't work until https://github.com/mi6/ic-ui-kit/pull/3852 has been merged in the next release, but I've tested it by checking the components out locally.
https://github.com/mi6/ic-ui-kit/issues/3732
> docs(root): add code example for new data list css prop

- src/content/structured/components/time-input/code.mdx
- src/content/structured/components/time-input/guidance.mdx
- src/content/structured/components/toasts/guidance.mdx
- src/content/structured/components/toggle-buttons/guidance.mdx
- src/content/structured/components/tooltips/guidance.mdx
- src/content/structured/components/top-nav/guidance.mdx
- src/content/structured/components/tree-view/accessibility.mdx
- src/content/structured/components/tree-view/code.mdx
- src/content/structured/components/tree-view/guidance.mdx
- src/content/structured/components/typography/guidance.mdx
- src/icds-pages-data.json
- Add stand in-guidance and code pages for IcTimeInput
- Update canary-component-names.json file
- Update navPriority for guidance pages that follow the Time Input guidance page
#1614
> docs(root): add guidance and code pages for IcTimeInput

- src/templates/Homepage/index.tsx
Update homepage cards to not be a h4 and instead be a p tag under the hood
#1604
> 1604 home page cards heading hierarchy improvement 

- src/content/structured/components/side-nav/accessibility.mdx
- src/content/structured/components/side-nav/code.mdx
- src/content/structured/components/side-nav/guidance.mdx
remove the title tag from the svgs in side navigation code examples and add a short sentence explaining why it should be avoided
fix #1630
> docs(root): remove title tag from svgs in side nav code examples

- src/components/ComponentDetails/PropTable/PropDescription/index.tsx
- src/components/ComponentDetails/PropTable/index.tsx
Update component details default value to display like an object to fix issue where component details table would overlap the anchor nav
#1600
> 1600 comp details table overlaps anchor nav

- src/content/structured/components/card-horizontal/guidance.mdx
- src/content/structured/components/data-table/guidance.mdx
- src/content/structured/components/date-input/guidance.mdx
- src/content/structured/components/date-picker/guidance.mdx
- src/content/structured/components/pagination-bar/guidance.mdx
- src/content/structured/components/time-input/guidance.mdx
- src/content/structured/components/tree-view/guidance.mdx
Updated canary storybook links on canary component pages to point to storybooks on the develop branch.
#1666
> fix(root): update out of date canary storybook links
